name: Check IP adress

on:
  workflow_dispatch:
    inputs:
      iter:
        description: 'How many times to check for IP adress'
        required: true 


jobs:  
  dummy_job:
    name: "Dummy job"  
    runs-on: ubuntu-latest
    steps:
    - name: Find public IP
      run: |
        echo "Starting"
        ips=()
        for i in $(seq 1 ${{ github.event.inputs.iter }}); do
            ipv4=`curl -s ifconfig.me`
            ips+=("$ipv4")
        done
        unique_ips=($(echo "${ips[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
        echo "Unique IP addresses:"
        echo "${unique_ips[@]}"
        echo "Done"



    
        


###################################
# deploy code Bravo Fam Mover - V2
# migrate database and RDFox  - V2     
###################################
