name: Check IP adress

on:
  workflow_dispatch:
    inputs:
      iter:
        description: 'How many times to check for IP adress'
        required: true 


jobs:  
  dummy_job:
    name: "Dummy job"  
    runs-on: ubuntu-latest
    steps:
    - name: Find public IP
      run: |
        echo "Starting"
        for i in $(seq 1 ${{ github.event.inputs.iter }}); do
            ipv4=`curl ifconfig.me`
            echo $ipv4
        done
        echo "Done"



    
        


###################################
# deploy code Bravo Fam Mover - V2
# migrate database and RDFox  - V2     
###################################
