name: "Merge ready check"

on:
  pull_request_review:
    types: [submitted]
    branches:
      - development

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/approved_labels.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
